### ISSUE TITLE
Bug: Generic input selector rule has side-effects

### ISSUE THREAD

**Issue by MattL75** [SAP/fundamental#1248]
**Describe the bug**
In scss/core/forms.scss line 242 there are generic input selectors being used without being specific to fundamental. This causes some unwanted side-effects for users.

SAP/fundamental-ngx#476

```
input[type=checkbox], // <-- causes unwanted side-effects
input[type=radio] { // <-- causes unwanted side-effects
```

> Is this issue related to a specific component?
Any input with type checkbox/radio

> What version of the Fiori Fundamentals are you using?
1.4.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
The linked issue's owner is on SAP FSM

> What front-end framework are you implementing in, e.g., Angular, React, etc.?
Fundamental-NGX

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xak** [comment]
We include a light reset of core elements to match the expected look and feel. Can you provide an example of how this is causing a problem? Are you getting clashes with other libraries? Our intention is to provide a convenience meaning a class is not required for every input. When would you use a radio button in a Fiori look and feel next to one with a different look and feel?

**Comment by desaroxx** [comment]
@xak We were acquired by SAP last year and are now in the process of restyling our fleet of "already in production" Angular-based apps to comply with _fundamental_'s look and feel. 

As soon as we include _fiori-fundamentals.css_ the "light reset of core elements" starts overriding our ALL of our input elements within an app. 

We can not risk taking the "big bang" approach with including _fiori-fundamentals.css_ and have a unknown number of input fields be affected.

We need to be able to migrate our apps gradually, meaning that we consciously migrate each input field individually.

What would make our life easier?
All CSS Rules are prefixed with `fd-` prefixed. This we can control where  _fiori-fundamentals.css_'s styles get applied.

**Comment by droshev** [comment]
I think fiori-fundamentals should not set rules for elements that are not using fundamental classes.
@saad-mo is there a way providing a solution for @desaroxx? It is blocking their adoption of fundamentals /implementation.

**Comment by bcullman** [comment]
@droshev: alternatively, fiori-fundamentals should allow for consumers to "opt-in" (or opt-out) for non-classed element style

**Comment by eboyer** [comment]
@bcullman @droshev ~ Do you guys have any thoughts on an "opt-out" approach if we were to leave the code as it is now AND provide some opt-in classes? Removing the base styles would be a breaking change for a major version, so we'll have to be sensitive of that if we end up doing it.

**Comment by ChristianKienle** [comment]
@bcullman @droshev @desaroxx what about integrating the styles in your app like this:

```scss
$fd-icons-path : './../node_modules/fiori-fundamentals/scss/icons/';
$fd-scss-font-path : './../node_modules/fiori-fundamentals/scss/fonts/';

@import './../node_modules/fiori-fundamentals/scss/core/root.scss';
@import './../node_modules/fiori-fundamentals/scss/settings';

.fiori {
  /* stylelint-disable-next-line declaration-no-important */
  font-size: 14px !important;
}

.fiori[data-fiori] {
  @import './../node_modules/fiori-fundamentals/scss/fonts';
  @import './../node_modules/fiori-fundamentals/scss/icons';
  @import './../node_modules/fiori-fundamentals/scss/core/forms.scss';
  @import './../node_modules/fiori-fundamentals/scss/core/elements.scss';
  @import './../node_modules/fiori-fundamentals/scss/layout';
  @import './../node_modules/fiori-fundamentals/scss/components';
  @import './../node_modules/fiori-fundamentals/scss/helpers';
}
```

By doing so you have no side effects by including the styles. You can opt-into Fiori Fundamentals anywhere just by writing:

```html
<div class="fiori" data-fiori>
   <!-- anything in here will get all the fiori fundamentals goodness -->
</div>
```
